# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Chore

pod 'CircleProgressBar', '~> 0.32’
	pod 'Parse'
	pod 'ParseUI'


  target 'ChoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
